### Single Elements

In [1]:
import numpy as np

Numpy indexes,are zero-based

In [2]:
# take the value from python list
my_vector = np.array([-17,-4,0,2,21,37,109])

In [3]:
my_vector

array([-17,  -4,   0,   2,  21,  37, 109])

#### select element

In [4]:
# select element
my_vector[0]

-17

#### change value

In [5]:
# change value
my_vector[0]= -102

In [6]:
my_vector

array([-102,   -4,    0,    2,   21,   37,  109])

#### access the third element from the end of this array

In [7]:
# access the third element from the end of this array
my_vector[-3]

21

#### Index divided by array size

In [8]:
# out of range
my_vector[305]

IndexError: index 305 is out of bounds for axis 0 with size 7

In [9]:
305 % 7

4

In [10]:
my_vector[ 305 % 7]

21

In [11]:
my_vector.size

7

In [12]:
my_vector[ 305 % my_vector.size]

21

### Two dimensional Arrays

In [13]:
my_array = np.arange(35)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

#### shape


In [14]:
# 将矩阵一维矩阵转化成7x5的二维矩阵
# accessing my_array.shape and setting it to a tuple
my_array.shape = (7,5)
my_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

#### access the third row

In [15]:
# access the third row
my_array[2]

array([10, 11, 12, 13, 14])

In [16]:
my_array[-2]

array([25, 26, 27, 28, 29])

#### access a single element

In [17]:
# access a single element
row = 5
column = 2
my_array[row,column]

27

In [18]:
my_array[row][column]

27

#### Three dimensional arrays

In [19]:
my_3D_array = np.arange(70)
my_3D_array.shape = (2,7,5)
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [20]:
my_3D_array[1]

array([[35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69]])

In [21]:
my_3D_array[1,3]

array([50, 51, 52, 53, 54])

In [22]:
my_3D_array[1,3,2]

52

In [23]:
my_3D_array[1,3,2] = 8888
my_3D_array

array([[[   0,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9],
        [  10,   11,   12,   13,   14],
        [  15,   16,   17,   18,   19],
        [  20,   21,   22,   23,   24],
        [  25,   26,   27,   28,   29],
        [  30,   31,   32,   33,   34]],

       [[  35,   36,   37,   38,   39],
        [  40,   41,   42,   43,   44],
        [  45,   46,   47,   48,   49],
        [  50,   51, 8888,   53,   54],
        [  55,   56,   57,   58,   59],
        [  60,   61,   62,   63,   64],
        [  65,   66,   67,   68,   69]]])

#### Boolean Mask arrays

In [24]:
my_vector = np.array([-17,-4,0,2,21,37,105])
my_vector

array([-17,  -4,   0,   2,  21,  37, 105])

In [25]:
zero_mod_7_mask = 0 == (my_vector % 7)
zero_mod_7_mask

array([False, False,  True, False,  True, False,  True])

In [26]:
# 过滤掉false的元素
sub_array = my_vector[ zero_mod_7_mask ]
sub_array

array([  0,  21, 105])

In [27]:
sub_array>0

array([False,  True,  True])

In [28]:
sub_array[ sub_array > 0]

array([ 21, 105])

#### Numpy logical operators

+ The first use the python logical operator
+ The second use the numpy's logical operator and function

**When deal with large arrays,numpy's functions will probably more efficient**

In [29]:
mod_test = 0 == (my_vector % 7)
mod_test

array([False, False,  True, False,  True, False,  True])

In [30]:
positive_test = my_vector > 0
positive_test

array([False, False, False,  True,  True,  True,  True])

In [31]:
combine_mask = np.logical_and(mod_test,positive_test)
combine_mask

array([False, False, False, False,  True, False,  True])

In [32]:
my_vector[ combine_mask ]

array([ 21, 105])

### Broadcasting

In order to perform broadcasting correctly,we need to know the attribute of arrays

These attribute include **shapes**,**number dimensions**,**size** and **data types**

In [33]:
my_3D_array = np.arange(70)
my_3D_array.shape = (2,7,5)
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [34]:
# shape
my_3D_array.shape

(2, 7, 5)

In [35]:
# number of the dimensions
my_3D_array.ndim

3

In [36]:
# size: number of elements
my_3D_array.size

70

In [37]:
# data type  for each element
my_3D_array.dtype

dtype('int64')

**Broadcasting rules** 就是矩阵之间运算需要遵循的规则

+ To test operation is compatible

NumPy's broadcasting rules treat scalers as having a size equal to one

In [38]:
5 * my_3D_array -2

array([[[ -2,   3,   8,  13,  18],
        [ 23,  28,  33,  38,  43],
        [ 48,  53,  58,  63,  68],
        [ 73,  78,  83,  88,  93],
        [ 98, 103, 108, 113, 118],
        [123, 128, 133, 138, 143],
        [148, 153, 158, 163, 168]],

       [[173, 178, 183, 188, 193],
        [198, 203, 208, 213, 218],
        [223, 228, 233, 238, 243],
        [248, 253, 258, 263, 268],
        [273, 278, 283, 288, 293],
        [298, 303, 308, 313, 318],
        [323, 328, 333, 338, 343]]])

In [39]:
left_mat = np.arange(6).reshape((2,3))
right_mat = np.arange(15).reshape((3,5))


In [40]:
np.dot(left_mat,right_mat)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

#### Operations along axes

In [41]:
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

#### sum


In [42]:
my_3D_array.sum()

2415

In [43]:
my_3D_array.sum(axis=0)

array([[ 35,  37,  39,  41,  43],
       [ 45,  47,  49,  51,  53],
       [ 55,  57,  59,  61,  63],
       [ 65,  67,  69,  71,  73],
       [ 75,  77,  79,  81,  83],
       [ 85,  87,  89,  91,  93],
       [ 95,  97,  99, 101, 103]])

In [44]:
my_3D_array.sum(axis=1)

array([[105, 112, 119, 126, 133],
       [350, 357, 364, 371, 378]])

In [45]:
my_3D_array.sum(axis=2)

array([[ 10,  35,  60,  85, 110, 135, 160],
       [185, 210, 235, 260, 285, 310, 335]])

In [46]:
my_2D_array = np.ones(35,dtype='int64').reshape((7,5))*3
my_2D_array


array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [47]:
my_2D_array = np.random.random((7,5))
my_2D_array

array([[0.0468911 , 0.04329934, 0.95225564, 0.51861296, 0.45218547],
       [0.3577821 , 0.63808404, 0.5802222 , 0.65503559, 0.11458762],
       [0.03963297, 0.68034684, 0.690839  , 0.35781053, 0.54304311],
       [0.06016523, 0.18331361, 0.32573531, 0.96672614, 0.69574094],
       [0.92219228, 0.81199475, 0.96770518, 0.97033172, 0.39575002],
       [0.25062847, 0.43032675, 0.1117085 , 0.07192191, 0.68828254],
       [0.6444946 , 0.21994571, 0.62272818, 0.62139584, 0.84274348]])

In [48]:
# 设置精度
# set precision for floating point variables
np.set_printoptions(precision=4)
my_3D_array * my_2D_array


array([[[0.0000e+00, 4.3299e-02, 1.9045e+00, 1.5558e+00, 1.8087e+00],
        [1.7889e+00, 3.8285e+00, 4.0616e+00, 5.2403e+00, 1.0313e+00],
        [3.9633e-01, 7.4838e+00, 8.2901e+00, 4.6515e+00, 7.6026e+00],
        [9.0248e-01, 2.9330e+00, 5.5375e+00, 1.7401e+01, 1.3219e+01],
        [1.8444e+01, 1.7052e+01, 2.1290e+01, 2.2318e+01, 9.4980e+00],
        [6.2657e+00, 1.1188e+01, 3.0161e+00, 2.0138e+00, 1.9960e+01],
        [1.9335e+01, 6.8183e+00, 1.9927e+01, 2.0506e+01, 2.8653e+01]],

       [[1.6412e+00, 1.5588e+00, 3.5233e+01, 1.9707e+01, 1.7635e+01],
        [1.4311e+01, 2.6161e+01, 2.4369e+01, 2.8167e+01, 5.0419e+00],
        [1.7835e+00, 3.1296e+01, 3.2469e+01, 1.7175e+01, 2.6609e+01],
        [3.0083e+00, 9.3490e+00, 1.6938e+01, 5.1236e+01, 3.7570e+01],
        [5.0721e+01, 4.5472e+01, 5.5159e+01, 5.6279e+01, 2.3349e+01],
        [1.5038e+01, 2.6250e+01, 6.9259e+00, 4.5311e+00, 4.4050e+01],
        [4.1892e+01, 1.4516e+01, 4.1723e+01, 4.2255e+01, 5.8149e+01]]])

NumPy is using its broadcasting rules to check ompatibility between my_3D_array and my_2D_array.

In [49]:
my_vector = np.arange(5)*7
my_vector[0]=-1
my_vector

array([-1,  7, 14, 21, 28])

In [50]:
my_3D_array / my_vector

array([[[ -0.    ,   0.1429,   0.1429,   0.1429,   0.1429],
        [ -5.    ,   0.8571,   0.5   ,   0.381 ,   0.3214],
        [-10.    ,   1.5714,   0.8571,   0.619 ,   0.5   ],
        [-15.    ,   2.2857,   1.2143,   0.8571,   0.6786],
        [-20.    ,   3.    ,   1.5714,   1.0952,   0.8571],
        [-25.    ,   3.7143,   1.9286,   1.3333,   1.0357],
        [-30.    ,   4.4286,   2.2857,   1.5714,   1.2143]],

       [[-35.    ,   5.1429,   2.6429,   1.8095,   1.3929],
        [-40.    ,   5.8571,   3.    ,   2.0476,   1.5714],
        [-45.    ,   6.5714,   3.3571,   2.2857,   1.75  ],
        [-50.    ,   7.2857,   3.7143,   2.5238,   1.9286],
        [-55.    ,   8.    ,   4.0714,   2.7619,   2.1071],
        [-60.    ,   8.7143,   4.4286,   3.    ,   2.2857],
        [-65.    ,   9.4286,   4.7857,   3.2381,   2.4643]]])

In [51]:
my_3D_array % my_vector

array([[[ 0,  1,  2,  3,  4],
        [ 0,  6,  7,  8,  9],
        [ 0,  4, 12, 13, 14],
        [ 0,  2,  3, 18, 19],
        [ 0,  0,  8,  2, 24],
        [ 0,  5, 13,  7,  1],
        [ 0,  3,  4, 12,  6]],

       [[ 0,  1,  9, 17, 11],
        [ 0,  6,  0,  1, 16],
        [ 0,  4,  5,  6, 21],
        [ 0,  2, 10, 11, 26],
        [ 0,  0,  1, 16,  3],
        [ 0,  5,  6,  0,  8],
        [ 0,  3, 11,  5, 13]]])

### Creating Structured Arrays

In [55]:
# data definition
person_data_def = [('name','S6'),('height','f8'),('weight','f8'),('age','i8')]
person_data_def

[('name', 'S6'), ('height', 'f8'), ('weight', 'f8'), ('age', 'i8')]

In [56]:
people_array = np.zeros((4),dtype=person_data_def)
people_array

array([(b'', 0., 0., 0), (b'', 0., 0., 0), (b'', 0., 0., 0),
       (b'', 0., 0., 0)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [59]:
people_array[3] = ('Q10Viking',73,120,23)

In [61]:
people_array[0] = ('Alpha',65,112,23)

In [62]:
people_array

array([(b'Alpha', 65., 112., 23), (b'',  0.,   0.,  0),
       (b'',  0.,   0.,  0), (b'Q10Vik', 73., 120., 23)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [63]:
people_array[0:]

array([(b'Alpha', 65., 112., 23), (b'',  0.,   0.,  0),
       (b'',  0.,   0.,  0), (b'Q10Vik', 73., 120., 23)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [85]:
ages = people_array['age']
ages


array([23,  0,  0, 23])

In [86]:
ages[0]

23

In [69]:
make_youthful = ages / 2
make_youthful

array([11.5,  0. ,  0. , 11.5])

### Multi-dimensional Structured Arrays

In [71]:
people_big_array = np.zeros((4,3,2),dtype=person_data_def)
people_big_array

array([[[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [73]:
people_big_array[3,2,1] = ('Echo',68,155,46)

In [75]:
people_big_array

array([[[(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)]],

       [[(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)]],

       [[(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)]],

       [[(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'',  0.,   0.,  0)],
        [(b'',  0.,   0.,  0), (b'Echo', 68., 155., 46)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [77]:
people_big_array[['height']]

array([[[( 0.,), ( 0.,)],
        [( 0.,), ( 0.,)],
        [( 0.,), ( 0.,)]],

       [[( 0.,), ( 0.,)],
        [( 0.,), ( 0.,)],
        [( 0.,), ( 0.,)]],

       [[( 0.,), ( 0.,)],
        [( 0.,), ( 0.,)],
        [( 0.,), ( 0.,)]],

       [[( 0.,), ( 0.,)],
        [( 0.,), ( 0.,)],
        [( 0.,), (68.,)]]], dtype=[('height', '<f8')])

In [78]:
people_big_array[['height','weight']]

array([[[( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)]],

       [[( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)]],

       [[( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)]],

       [[( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), (68., 155.)]]],
      dtype=[('height', '<f8'), ('weight', '<f8')])

### Creating Record Array

This wrapping allows **field access** by attibute on an array object.

In [81]:
person_record_array = np.rec.array([('Delta',73,205,34),('Alpha',65,112,23)],dtype=person_data_def)
person_record_array

rec.array([(b'Delta', 73., 205., 34), (b'Alpha', 65., 112., 23)],
          dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [82]:
# use the attribute
person_record_array[0].age

34