### Views and Copies

In [1]:
import numpy as np


In [3]:
mi_casa = np.array([-45,-31,-12,0,2,25,51,99])

In [5]:
su_casa = mi_casa

#### Memory Location Same or Different

In [6]:
# reference equality
mi_casa is su_casa

True

In [7]:
id(mi_casa)

139620529305520

In [8]:
id(su_casa)

139620529305520

#### Value equality

In [9]:
mi_casa == su_casa

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [10]:
su_casa[4] = 1010

In [11]:
su_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

In [12]:
mi_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

**mi_casa and su_casa are actually references to the same location in memory**

In [13]:
tree_house = np.array([-45,-31,-12,0,2,25,51,99])

In [14]:
tree_house == su_casa

array([ True,  True,  True,  True, False,  True,  True,  True])

In [16]:
id(tree_house)

139620528863152

In [17]:
id(mi_casa)

139620529305520

In [18]:
tree_house[0] = 214

In [19]:
tree_house

array([214, -31, -12,   0,   2,  25,  51,  99])

In [20]:
mi_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

In [21]:
tree_house == mi_casa

array([False,  True,  True,  True, False,  True,  True,  True])

In [22]:
tree_house is mi_casa

False

#### View a shallow copy

In [27]:
farm_house = tree_house.view()
farm_house.shape = (2,4)

In [28]:
tree_house

array([214, -31, -12,   0,   2,  25,  51,  99])

In [29]:
farm_house

array([[214, -31, -12,   0],
       [  2,  25,  51,  99]])

In [30]:
tree_house[3] = -111

In [31]:
farm_house

array([[ 214,  -31,  -12, -111],
       [   2,   25,   51,   99]])

**The elements of the farm_house and tree_house are located in the same location in main memory**

#### Deep copy

In [32]:
dog_house = np.copy(tree_house)
dog_house[0] = -121
dog_house

array([-121,  -31,  -12, -111,    2,   25,   51,   99])

In [33]:
tree_house

array([ 214,  -31,  -12, -111,    2,   25,   51,   99])

In [34]:
id(tree_house)

139620528863152

In [35]:
id(dog_house)

139620455895888

**The difference between view and copies are that copies duplicate information in different location in memory**

### Attributes of NumPy arrays

In [36]:
a = np.array(np.arange(24)).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [37]:
# the number dimensions in a
a.ndim

3

In [38]:
# the size of the a
a.size

24

In [39]:
# the shape of the a
a.shape

(2, 3, 4)

In [40]:
# the data type of the a
a.dtype

dtype('int64')

In [41]:
# means 8 bytes
a.itemsize

8

In [42]:
# the type of a
type(a)

numpy.ndarray

### Adding and Removing Elements from NumPy Arrays

In [45]:
a = np.array(np.arange(24)).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

#### append function

In [53]:
# a is the source,and additional elements would be appended
b = np.append(a,[5,6,7,8])

In [48]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  5,  6,  7,  8])

In [49]:
b.shape

(28,)

In [50]:
b.reshape((7,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 5,  6,  7,  8]])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  5,  6,  7,  8])

In [52]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [54]:
c = np.array(np.arange(24)).reshape(2,3,4)*10+3

In [55]:
c

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [56]:
np.append(a,c,axis=0)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [57]:
np.append(a,c,axis=0).shape

(4, 3, 4)

In [58]:
np.append(a,c,axis=1)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [59]:
np.append(a,c,axis=1).shape

(2, 6, 4)

In [60]:
np.append(a,c,axis=2)

array([[[  0,   1,   2,   3,   3,  13,  23,  33],
        [  4,   5,   6,   7,  43,  53,  63,  73],
        [  8,   9,  10,  11,  83,  93, 103, 113]],

       [[ 12,  13,  14,  15, 123, 133, 143, 153],
        [ 16,  17,  18,  19, 163, 173, 183, 193],
        [ 20,  21,  22,  23, 203, 213, 223, 233]]])

In [61]:
np.append(a,c,axis=2).shape

(2, 3, 8)

#### hstack function
It is a convenience method because it eliminates one parameter,the axis parameter

In [62]:
my_hay_stack = np.hstack((a,c))
my_hay_stack 

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [64]:
my_hay_stack[0,0,2] = 999
my_hay_stack

array([[[  0,   1, 999,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [65]:
# a value not change
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

use append function


In [71]:
my_append_array = np.append(a,c,axis=1)
my_append_array

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [72]:
my_append_array[0,0,2]=999
my_append_array

array([[[  0,   1, 999,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [73]:
# a value also not change
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

#### insert function

In [74]:
c

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [75]:
# source,position,value,dim
after_insert_array = np.insert(c,1,333,axis=0)
after_insert_array

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[333, 333, 333, 333],
        [333, 333, 333, 333],
        [333, 333, 333, 333]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [76]:
# source,position,value,dim
after_insert_array = np.insert(c,1,333,axis=1)
after_insert_array

array([[[  3,  13,  23,  33],
        [333, 333, 333, 333],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [333, 333, 333, 333],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [77]:
# source,position,value,dim
after_insert_array = np.insert(c,1,333,axis=2)
after_insert_array

array([[[  3, 333,  13,  23,  33],
        [ 43, 333,  53,  63,  73],
        [ 83, 333,  93, 103, 113]],

       [[123, 333, 133, 143, 153],
        [163, 333, 173, 183, 193],
        [203, 333, 213, 223, 233]]])

#### delete function

In [78]:
d = np.empty(c.shape)
d

array([[[0.000e+000, 4.941e-323, 9.881e-323, 1.482e-322],
        [1.976e-322, 2.470e-322, 2.964e-322, 3.458e-322],
        [3.953e-322, 4.447e-322, 4.941e-322, 5.435e-322]],

       [[5.929e-322, 6.423e-322, 6.917e-322, 7.411e-322],
        [7.905e-322, 8.399e-322, 8.893e-322, 9.387e-322],
        [9.881e-322, 1.038e-321, 1.087e-321, 1.136e-321]]])

In [79]:
np.copyto(d,c)
d

array([[[  3.,  13.,  23.,  33.],
        [ 43.,  53.,  63.,  73.],
        [ 83.,  93., 103., 113.]],

       [[123., 133., 143., 153.],
        [163., 173., 183., 193.],
        [203., 213., 223., 233.]]])

In [80]:
# source,pos,dim
np.delete(d,1,axis=0)

array([[[  3.,  13.,  23.,  33.],
        [ 43.,  53.,  63.,  73.],
        [ 83.,  93., 103., 113.]]])

In [81]:
np.delete(d,1,axis=1)

array([[[  3.,  13.,  23.,  33.],
        [ 83.,  93., 103., 113.]],

       [[123., 133., 143., 153.],
        [203., 213., 223., 233.]]])

In [82]:
np.delete(d,1,axis=2)

array([[[  3.,  23.,  33.],
        [ 43.,  63.,  73.],
        [ 83., 103., 113.]],

       [[123., 143., 153.],
        [163., 183., 193.],
        [203., 223., 233.]]])

### Joining and Splitting arrays

In [84]:
a = np.array(([1,2],[3,4]))
a

array([[1, 2],
       [3, 4]])

In [89]:
b = np.array([[5,6]])
b

array([[5, 6]])

#### concatenate

In [87]:
together = np.concatenate((a,b),axis=0)

In [88]:
together

array([[1, 2],
       [3, 4],
       [5, 6]])

In [90]:
together.shape

(3, 2)

In [92]:
together[1,1] = 555

In [93]:
together

array([[  1,   2],
       [  3, 555],
       [  5,   6]])

In [94]:
# not change
a

array([[1, 2],
       [3, 4]])

In [95]:
c = np.array(([1,2],[3,4]))*3+5
c

array([[ 8, 11],
       [14, 17]])

In [96]:
np.concatenate((a,c),axis=1)

array([[ 1,  2,  8, 11],
       [ 3,  4, 14, 17]])

np.append(a,c,axis=1)

In [97]:
# the same
np.append(a,c,axis=1)

array([[ 1,  2,  8, 11],
       [ 3,  4, 14, 17]])

#### stack function

按不同的维度从新组成新的数据，也就是将dim 0移动到目标维度处

In [111]:

arrays = np.array(np.arange(60)).reshape((5,3,4))
arrays

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]],

       [[36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]]])

In [112]:
arrays.shape

(5, 3, 4)

In [113]:
stack0 = np.stack(arrays,axis=0)
stack0

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]],

       [[36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]]])

In [114]:
stack0.shape

(5, 3, 4)

In [115]:
stack1 = np.stack(arrays,axis=1)
stack1

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15],
        [24, 25, 26, 27],
        [36, 37, 38, 39],
        [48, 49, 50, 51]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19],
        [28, 29, 30, 31],
        [40, 41, 42, 43],
        [52, 53, 54, 55]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23],
        [32, 33, 34, 35],
        [44, 45, 46, 47],
        [56, 57, 58, 59]]])

In [116]:
stack1.shape

(3, 5, 4)

In [117]:
stack2 = np.stack(arrays,axis=2)
stack2

array([[[ 0, 12, 24, 36, 48],
        [ 1, 13, 25, 37, 49],
        [ 2, 14, 26, 38, 50],
        [ 3, 15, 27, 39, 51]],

       [[ 4, 16, 28, 40, 52],
        [ 5, 17, 29, 41, 53],
        [ 6, 18, 30, 42, 54],
        [ 7, 19, 31, 43, 55]],

       [[ 8, 20, 32, 44, 56],
        [ 9, 21, 33, 45, 57],
        [10, 22, 34, 46, 58],
        [11, 23, 35, 47, 59]]])

In [118]:
stack2.shape

(3, 4, 5)

#### split

将产生关于array的列表

In [120]:
temp = np.arange(5)
temp

array([0, 1, 2, 3, 4])

In [121]:
np.split(temp,1)

[array([0, 1, 2, 3, 4])]

In [122]:
before_split = stack0
before_split.shape

(5, 3, 4)

只能根据shape中的维度中相应的数量分隔，如dim0 能分成5个数据，dim1 能分成3个

In [123]:
s0 = np.split(before_split,5,axis=0)
s0

[array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]]), array([[[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]), array([[[24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35]]]), array([[[36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]]]), array([[[48, 49, 50, 51],
         [52, 53, 54, 55],
         [56, 57, 58, 59]]])]

In [124]:
type(s0)

list

In [125]:
s0[1]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [126]:
s0[1].shape

(1, 3, 4)

In [132]:
s1 = np.split(before_split,3,axis=1)
s1

[array([[[ 0,  1,  2,  3]],
 
        [[12, 13, 14, 15]],
 
        [[24, 25, 26, 27]],
 
        [[36, 37, 38, 39]],
 
        [[48, 49, 50, 51]]]), array([[[ 4,  5,  6,  7]],
 
        [[16, 17, 18, 19]],
 
        [[28, 29, 30, 31]],
 
        [[40, 41, 42, 43]],
 
        [[52, 53, 54, 55]]]), array([[[ 8,  9, 10, 11]],
 
        [[20, 21, 22, 23]],
 
        [[32, 33, 34, 35]],
 
        [[44, 45, 46, 47]],
 
        [[56, 57, 58, 59]]])]

In [127]:
s2 = np.split(before_split,4,axis=2)
s2

[array([[[ 0],
         [ 4],
         [ 8]],
 
        [[12],
         [16],
         [20]],
 
        [[24],
         [28],
         [32]],
 
        [[36],
         [40],
         [44]],
 
        [[48],
         [52],
         [56]]]), array([[[ 1],
         [ 5],
         [ 9]],
 
        [[13],
         [17],
         [21]],
 
        [[25],
         [29],
         [33]],
 
        [[37],
         [41],
         [45]],
 
        [[49],
         [53],
         [57]]]), array([[[ 2],
         [ 6],
         [10]],
 
        [[14],
         [18],
         [22]],
 
        [[26],
         [30],
         [34]],
 
        [[38],
         [42],
         [46]],
 
        [[50],
         [54],
         [58]]]), array([[[ 3],
         [ 7],
         [11]],
 
        [[15],
         [19],
         [23]],
 
        [[27],
         [31],
         [35]],
 
        [[39],
         [43],
         [47]],
 
        [[51],
         [55],
         [59]]])]

#### Array Shape Manipulate

In [133]:
my_start_array = np.array(np.arange(24))
my_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

#### reshape

In [134]:
my_start_array.shape

(24,)

In [136]:
my_3_8_array = my_start_array.reshape((3,8))
my_3_8_array


array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [137]:
my_3_8_array[0,0]=1234

In [138]:
# 说明是浅复制
my_start_array

array([1234,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23])

#### ravel

It returns a array

In [139]:
# we converted a three x eight array to one dimension array
my_ravel_array = my_3_8_array.ravel()
my_ravel_array

array([1234,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23])

In [140]:
my_ravel_array.shape

(24,)

#### flat
it returns an iterator

In [141]:
for n in my_3_8_array.flat:
    print(n)

1234
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


### Rearranging Array Elements

In [142]:
my_start_array = np.array(np.arange(24))
my_3_8_array = my_start_array.reshape((3,8))
my_2_3_4_array = my_3_8_array.reshape((2,3,4))

#### fliplr "flip left right"

Flip array in  the left/right direction

In [143]:
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [144]:
np.fliplr(my_3_8_array)

array([[ 7,  6,  5,  4,  3,  2,  1,  0],
       [15, 14, 13, 12, 11, 10,  9,  8],
       [23, 22, 21, 20, 19, 18, 17, 16]])

In [145]:
my_2_3_4_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [146]:
np.fliplr(my_2_3_4_array)

array([[[ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[20, 21, 22, 23],
        [16, 17, 18, 19],
        [12, 13, 14, 15]]])

#### flipud

In [147]:
np.flipud(my_3_8_array)

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5,  6,  7]])

In [149]:
np.flipud(my_2_3_4_array)

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [150]:
#### roll

In [151]:
my_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [152]:
# source position
np.roll(my_start_array,5)

array([19, 20, 21, 22, 23,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
       12, 13, 14, 15, 16, 17, 18])

In [153]:
np.roll(my_start_array,-5)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23,  0,  1,  2,  3,  4])

In [154]:
np.roll(my_2_3_4_array,2)

array([[[22, 23,  0,  1],
        [ 2,  3,  4,  5],
        [ 6,  7,  8,  9]],

       [[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]]])

In [155]:
np.roll(my_2_3_4_array,-2)

array([[[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [10, 11, 12, 13]],

       [[14, 15, 16, 17],
        [18, 19, 20, 21],
        [22, 23,  0,  1]]])

#### rot90

In [156]:
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [157]:
np.rot90(my_3_8_array)

array([[ 7, 15, 23],
       [ 6, 14, 22],
       [ 5, 13, 21],
       [ 4, 12, 20],
       [ 3, 11, 19],
       [ 2, 10, 18],
       [ 1,  9, 17],
       [ 0,  8, 16]])

**Rotate 90 has a parameter K which allows us to rotate arrays in a negative direction**

In [159]:
np.rot90(my_3_8_array,k=-1)

array([[16,  8,  0],
       [17,  9,  1],
       [18, 10,  2],
       [19, 11,  3],
       [20, 12,  4],
       [21, 13,  5],
       [22, 14,  6],
       [23, 15,  7]])

### Transpose-like Operations

#### transpose function 重要

**将矩阵（i,j）转化成(j.i)**

In [160]:
my_start_array = np.array(np.arange(24))
my_3_8_array = my_start_array.reshape((3,8))
my_2_3_4_array = my_3_8_array.reshape((2,3,4))

In [162]:
my_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [163]:
np.transpose(my_start_array)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [164]:
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [165]:
np.transpose(my_3_8_array)

array([[ 0,  8, 16],
       [ 1,  9, 17],
       [ 2, 10, 18],
       [ 3, 11, 19],
       [ 4, 12, 20],
       [ 5, 13, 21],
       [ 6, 14, 22],
       [ 7, 15, 23]])

In [166]:
my_2_3_4_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [176]:
np.transpose(my_2_3_4_array,axes=(0,2,1))

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])

#### swapaxes

In [178]:
my_2_3_4_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [177]:
 np.swapaxes(my_2_3_4_array,1,0)

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

#### rollaxis

In [180]:
my_2_3_4_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [179]:
np.rollaxis(my_2_3_4_array,0,2)

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

+ Use np.transpose to permute all the axes at once

+ Use np.swapaxes to swap any two axes

+ Use np.rollaxis to "rotate" the axes

### Tiling Arrays

Construct an array by repeating A the number of times given by reps

In [181]:
my_start_array = np.array(np.arange(12))
my_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [182]:
np.tile(my_start_array,3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,
        5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10, 11])

In [183]:
# we can chain the functions together
np.tile(my_start_array,3).reshape((3,12))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [186]:
#  a another example
my_second_array = np.array(np.arange(7))
my_second_array

array([0, 1, 2, 3, 4, 5, 6])

In [188]:
tile_1 = np.tile(my_second_array,(3,1))
tile_1

array([[0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6]])

In [189]:
tile_2 = np.tile(tile_1,(2,2))
tile_2

array([[0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6]])

In [191]:
tile_3 = np.tile(tile_2,(3,1))
tile_3

array([[0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6]])

#### repeat function

In [193]:
my_second_array

array([0, 1, 2, 3, 4, 5, 6])

In [194]:
np.repeat(my_second_array,3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6])

In [196]:
my_repeatable_array = np.array(np.arange(24)).reshape(2,3,4)
my_repeatable_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [197]:
np.repeat(my_repeatable_array,2,axis=0)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [199]:
np.repeat(my_repeatable_array,2,axis=1)

array([[[ 0,  1,  2,  3],
        [ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [20, 21, 22, 23]]])

In [200]:
np.repeat(my_repeatable_array,2,axis=2)

array([[[ 0,  0,  1,  1,  2,  2,  3,  3],
        [ 4,  4,  5,  5,  6,  6,  7,  7],
        [ 8,  8,  9,  9, 10, 10, 11, 11]],

       [[12, 12, 13, 13, 14, 14, 15, 15],
        [16, 16, 17, 17, 18, 18, 19, 19],
        [20, 20, 21, 21, 22, 22, 23, 23]]])