#### Create NumPy arrays using Python's "array like" data types

In [1]:
import numpy as np

#### version

In [3]:
# NumPy version
print(np.__version__)

1.15.2


##### array

In [4]:
# create python list
my_list =  [-17,0,4,5,9]
# create NumPy array from pytho list
my_array_from_list = np.array(my_list)
my_array_from_list

array([-17,   0,   4,   5,   9])

In [6]:
# multiply every element
my_array_from_list * 10

array([-170,    0,   40,   50,   90])

In [9]:
# create a python tuple
my_tuple = (14,-3.54,5+7j)

# data types within NumPy are same

np.array(my_tuple)

array([14.  +0.j, -3.54+0.j,  5.  +7.j])

#### Difference between python and numpy data structures

In [10]:
my_tuple * 6

(14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j))

In [11]:
# multiplication operator
np.array(my_tuple) * 6


array([ 84.   +0.j, -21.24 +0.j,  30.  +42.j])

#### Intrinsic Numpy array creation using NumPy's method

#####  [arange](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html)

In [13]:
# stop
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [14]:
# start,stop
np.arange(10,23)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

###### See the size of array

In [15]:
np.arange(10,23)-10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
np.arange(10,23) - 10 + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [18]:
len(np.arange(10,23))

13

In [21]:
my_range_array = np.arange(10,23)
my_range_array.size

13

##### parameters 

In [22]:
# start,stop,step
np.arange(10,23,5)

array([10, 15, 20])

In [24]:
# start,stop,step
np.arange(10,26,5)

array([10, 15, 20, 25])

In [26]:
np.arange(26,step=5)


array([ 0,  5, 10, 15, 20, 25])

In [28]:
np.arange(0,26,step=5)

array([ 0,  5, 10, 15, 20, 25])

#### linspace(),zeros(),ones(),and NumPy data types

##### [linspace](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.linspace.html)

In [29]:
# start, stop, num
np.linspace(5,15,9)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ])

In [32]:
# see the step
my_linspace = np.linspace(5,15,9,retstep=True)
my_linspace

(array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ]), 1.25)

In [34]:
my_linspace[1]

1.25

##### zeros

In [35]:
# with floating point values
np.zeros(5)

array([0., 0., 0., 0., 0.])

##### ones

In [36]:
# with floating point values
np.ones(5)

array([1., 1., 1., 1., 1.])

##### Multi-dimensional arrays

In [40]:
# create 2 dimensional array
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
# create 3 dimensional array
np.zeros((2,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

##### data type parameter [【dtype】](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html)

In [43]:
# with int values
np.ones(5,dtype='int64')

array([1, 1, 1, 1, 1])

In [44]:
np.ones(5)

array([1., 1., 1., 1., 1.])